# Generated by Django 2.0.3 on 2020-05-19 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200519_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add',
            name='prize',
            field=models.FloatField(blank=True),
        ),
    ]
