# Generated by Django 2.0.3 on 2020-05-19 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20200519_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add',
            name='prize',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='sub',
            name='small_prize',
            field=models.FloatField(blank=True),
        ),
    ]
